FROM node:8.15.0
RUN mkdir -p /usr/src/bitcore
WORKDIR /usr/src/bitcore
COPY . /usr/src/bitcore

RUN npm install -g cnpm

RUN cnpm install

EXPOSE 3000

CMD ["npm", "--prefix=./packages/bitcore-node", "start"]